;;; Run in separate processes with QUASAR_IMPORT_TEST_MODE=write/read/abort/empty and a fresh
;;; QUASAR_IMPORT_TEST_DB. Fixture JSON comes from a production browser or portable source adapter.
(require :asdf)
(asdf:load-system :quasar-control)
(defun wi-object (&rest entries) (apply #'quasar.protocol:json-object entries))
(defun wi-call (plane command payload &optional (expected-status "ok"))
  (let ((response nil))
    (quasar.control-plane:submit-command plane
      (quasar.protocol:encode
       (wi-object (cons "protocol" quasar.protocol:+protocol-version+)
        (cons "id" (format nil "wireless-~A" (gensym)))
        (cons "command" command) (cons "payload" payload)
        (cons "metadata" (wi-object (cons "client" "wireless-native-test") (cons "workspace" "default")))))
      (lambda (value) (setf response value)))
    (loop repeat 1000 until response do (sleep .01))
    (assert response () "Control plane timed out")
    (let ((parsed (jsown:parse response)))
      (assert (equal expected-status (jsown:val parsed "status")) () "Command failed: ~A" response)
      (if (equal expected-status "ok") (jsown:val parsed "result") parsed))))
(let* ((path (uiop:getenv "QUASAR_IMPORT_TEST_DB"))
       (fixture (uiop:getenv "QUASAR_IMPORT_TEST_FIXTURE"))
       (mode (uiop:getenv "QUASAR_IMPORT_TEST_MODE"))
       (documents (jsown:parse (uiop:read-file-string fixture)))
       (readback nil)
       (store (quasar.store:make-tek9-store :path path))
       (plane (quasar.control-plane:start-control-plane (quasar.control-plane:make-control-plane :store store))))
  (unwind-protect
       (progn
         (when (member mode '("write" "abort") :test #'equal)
           (let* ((begin (wi-call plane "document.import.begin" (wi-object)))
                  (session (jsown:val begin "sessionId")))
             (let ((chunk (wi-object (cons "sessionId" session) (cons "sequence" 0)
                            (cons "operations" (apply #'quasar.protocol:json-array
                              (mapcar (lambda (doc) (wi-object (cons "type" "document.create") (cons "payload" doc))) documents))))))
               (wi-call plane "document.import.chunk" chunk)
               (when (uiop:getenv "QUASAR_IMPORT_TEST_REPLAY")
                 (wi-call plane "document.import.chunk" chunk)))
             ;; Staged records and custody artifacts must not become visible early.
             (dolist (document documents)
               (wi-call plane "document.get" (wi-object (cons "id" (jsown:val document "id"))) "error"))
             (wi-call plane (if (equal mode "abort") "document.import.abort" "document.import.commit") (wi-object (cons "sessionId" session)))))
         (dolist (document documents)
           (if (member mode '("abort" "empty") :test #'equal)
               (wi-call plane "document.get" (wi-object (cons "id" (jsown:val document "id"))) "error")
               (let ((actual (wi-call plane "document.get" (wi-object (cons "id" (jsown:val document "id"))))))
                 (assert (equal (jsown:val actual "dtype") (jsown:val document "dtype")))
                 (dolist (entry (cdr document))
                   (assert (equalp (jsown:val actual (car entry)) (cdr entry)) () "Field ~A changed across Tek9 persistence" (car entry)))
                 (push actual readback))))
         (when (uiop:getenv "QUASAR_IMPORT_TEST_READBACK")
           (with-open-file (out (uiop:getenv "QUASAR_IMPORT_TEST_READBACK") :direction :output :if-exists :supersede)
             (write-string (quasar.protocol:encode (apply #'quasar.protocol:json-array (nreverse readback))) out)))
         (format t "~&PASS ~A: ~D production-adapter wireless documents via real staged Tek9/LMDB~%" mode (length documents)))
    (quasar.control-plane:stop-control-plane plane)
    (quasar.store:close-store store)))
