(in-package #:quasar.actors.melissa.transport)

(define-condition melissa-transport-error (error)
  ((message :initarg :message :reader melissa-transport-error-message)
   (retryable-p :initarg :retryable-p :initform nil
                :reader melissa-transport-error-retryable-p))
  (:report (lambda (condition stream)
             (write-string (melissa-transport-error-message condition) stream))))

(defun retryable-transport-condition-p (condition)
  (and (typep condition 'melissa-transport-error)
       (melissa-transport-error-retryable-p condition)))

(defun non-empty-string (value)
  (let ((text (and value (princ-to-string value))))
    (when text
      (let ((trimmed (string-trim '(#\Space #\Tab #\Newline #\Return) text)))
        (and (plusp (length trimmed)) trimmed)))))

(defun data-value (entity &rest keys)
  (let ((data (canonical-entity-data entity)))
    (loop for key in keys
          for value = (json-value data key nil)
          for normalized = (non-empty-string value)
          when normalized return normalized)))

(defun entity-name (entity)
  (or (data-value entity "full_name" "name" "display_name" "main" "value")
      (non-empty-string (canonical-entity-title entity))))

(defun query-pair (key value)
  (when-let ((normalized (non-empty-string value)))
    (format nil "~A=~A" (quri:url-encode key) (quri:url-encode normalized))))

(defun build-query (pairs)
  (format nil "~{~A~^&~}"
          (remove nil
                  (mapcar (lambda (pair)
                            (query-pair (car pair) (cdr pair)))
                          pairs))))

(defun endpoint (service)
  (cdr (assoc service
              '(("personator-search" . "https://personatorsearch.melissadata.net/WEB/doPersonatorSearch")
                ("people-business-search" . "https://search.melissadata.net/V5/WEB/contactsearch/docontactSearch")
                ("personator-consumer" . "https://personator.melissadata.net/V3/WEB/ContactVerify/doContactVerify")
                ("personator-identity" . "https://globalpersonator.melissadata.net/v1/doContactVerify")
                ("reverse-geocoder" . "https://reversegeo.melissadata.net/V3/WEB/ReverseGeoCode/doLookup")
                ("property" . "https://property.melissadata.net/v4/WEB/LookupProperty")
                ("global-address" . "https://address.melissadata.net/V3/WEB/GlobalAddress/doGlobalAddress")
                ("global-name" . "https://globalname.melissadata.net/V3/WEB/GlobalName/doGlobalName")
                ("global-phone" . "https://globalphone.melissadata.net/V4/WEB/GlobalPhone/doGlobalPhone")
                ("global-email" . "https://globalemail.melissadata.net/V4/WEB/GlobalEmail/doGlobalEmail")
                ("global-ip" . "https://globalip.melissadata.net/V4/WEB/IPLocation/doIPLocation"))
              :test #'string=)))

(defun option (options key &optional default)
  (getf options key default))

(defun entity-input (entity)
  (list
   :full (entity-name entity)
   :first (data-value entity "fname" "first_name" "first")
   :last (data-value entity "lname" "last_name" "last")
   :company (data-value entity "company" "org" "organization")
   :address1 (data-value entity "street" "address" "address_line_1" "address1")
   :address2 (data-value entity "street2" "address_line_2" "address2")
   :city (data-value entity "city" "locality")
   :state (data-value entity "state" "region" "admin_area")
   :postal (data-value entity "postal" "postal_code" "zip")
   :country (data-value entity "country" "country_code")
   :email (data-value entity "email" "email_address")
   :phone (data-value entity "phone" "phone_number" "telephone" "mobile")
   :ip (data-value entity "ip" "ip_address")
   :mak (data-value entity "mak" "melissa_address_key" "address_key")
   :mik (data-value entity "mik" "melissa_identity_key" "identity_key")
   :latitude (data-value entity "latitude" "lat")
   :longitude (data-value entity "longitude" "long" "lng" "lon")
   :apn (data-value entity "apn" "parcel_number" "parcel")
   :fips (data-value entity "fips" "county_fips")
   :account (data-value entity "account" "account_number")
   :free-form (data-value entity "free_form" "freeform" "main" "value")))

(defun required-input-present-p (service input)
  (flet ((has (&rest keys)
           (some (lambda (key) (non-empty-string (getf input key))) keys)))
    (cond
      ((string= service "reverse-geocoder")
       (and (has :latitude) (has :longitude)))
      ((string= service "global-phone") (has :phone))
      ((string= service "global-email") (has :email))
      ((string= service "global-ip") (has :ip))
      ((string= service "global-name") (has :full :company))
      ((string= service "global-address") (has :address1 :postal))
      ((string= service "people-business-search") (has :full :company :address1 :postal))
      ((string= service "personator-search") (has :full :address1 :email :phone :mak :mik))
      ((string= service "personator-consumer")
       (has :full :first :last :company :address1 :postal :email :phone :ip :mak :mik))
      ((string= service "personator-identity") (has :full :address1 :postal :email :phone))
      ((string= service "property") (has :mak :address1 :apn :fips :account :free-form))
      (t nil))))

(defun service-pairs (service config input options)
  (let ((country (or (getf input :country)
                     (melissa-config-default-country config))))
    (append
     (list (cons "id" (melissa-config-license-key config))
           (cons "t" (melissa-config-transmission-reference config)))
     (cond
       ((string= service "personator-search")
        (list (cons "full" (getf input :full))
              (cons "a1" (getf input :address1))
              (cons "city" (getf input :city))
              (cons "state" (getf input :state))
              (cons "postal" (getf input :postal))
              (cons "email" (getf input :email))
              (cons "phone" (getf input :phone))
              (cons "mak" (getf input :mak))
              (cons "mik" (getf input :mik))
              (cons "cols" (or (option options :columns)
                                (melissa-config-personator-columns config)))
              (cons "opt" (or (option options :options)
                               (melissa-config-personator-options config)))))
       ((string= service "people-business-search")
        (list (cons "anyname" (or (getf input :company) (getf input :full)))
              (cons "a1" (getf input :address1))
              (cons "loc" (getf input :city))
              (cons "adminarea" (getf input :state))
              (cons "postal" (getf input :postal))
              (cons "maxrecords" (or (option options :max-records) 10))
              (cons "matchlevel" (or (option options :match-level) 10))))
       ((string= service "personator-consumer")
        (list (cons "act" (or (option options :action) "Check"))
              (cons "opt" (option options :options))
              (cons "cols" (option options :columns))
              (cons "full" (getf input :full))
              (cons "first" (getf input :first))
              (cons "last" (getf input :last))
              (cons "comp" (getf input :company))
              (cons "a1" (getf input :address1))
              (cons "city" (getf input :city))
              (cons "state" (getf input :state))
              (cons "postal" (getf input :postal))
              (cons "ctry" country)
              (cons "email" (getf input :email))
              (cons "phone" (getf input :phone))
              (cons "ip" (getf input :ip))
              (cons "mak" (getf input :mak))
              (cons "mik" (getf input :mik))))
       ((string= service "personator-identity")
        (list (cons "act" (or (option options :action) "Check"))
              (cons "full" (getf input :full))
              (cons "phone" (getf input :phone))
              (cons "email" (getf input :email))
              (cons "a1" (getf input :address1))
              (cons "loc" (getf input :city))
              (cons "admarea" (getf input :state))
              (cons "postal" (getf input :postal))
              (cons "ctry" country)))
       ((string= service "reverse-geocoder")
        (list (cons "lat" (getf input :latitude))
              (cons "long" (getf input :longitude))
              (cons "dist" (or (option options :reverse-distance) 10))
              (cons "recs" (or (option options :reverse-records) 10))))
       ((string= service "property")
        (list (cons "mak" (getf input :mak))
              (cons "a1" (getf input :address1))
              (cons "a2" (getf input :address2))
              (cons "city" (getf input :city))
              (cons "state" (getf input :state))
              (cons "postal" (getf input :postal))
              (cons "country" country)
              (cons "apn" (getf input :apn))
              (cons "fips" (getf input :fips))
              (cons "account" (getf input :account))
              (cons "ff" (or (getf input :free-form) (getf input :address1)))))
       ((string= service "global-address")
        (list (cons "a1" (getf input :address1))
              (cons "a2" (getf input :address2))
              (cons "loc" (getf input :city))
              (cons "admarea" (getf input :state))
              (cons "postal" (getf input :postal))
              (cons "ctry" country)
              (cons "org" (getf input :company))
              (cons "opt" (or (option options :options) "OutputGeo:ON"))))
       ((string= service "global-name")
        (list (cons "full" (getf input :full))
              (cons "comp" (getf input :company))
              (cons "ctry" country)
              (cons "opt" (option options :options))))
       ((string= service "global-phone")
        (list (cons "phone" (getf input :phone))
              (cons "ctry" country)
              (cons "opt" (or (option options :options) "VerifyPhone:Express"))))
       ((string= service "global-email")
        (list (cons "email" (getf input :email))
              (cons "opt" (or (option options :options)
                               "VerifyMailbox:Express,DomainCorrection:OFF,TimeToWait:25"))))
       ((string= service "global-ip")
        (list (cons "ip" (getf input :ip))
              (cons "cols" (option options :columns))))
       (t (error "Unsupported Melissa service ~S." service)))
     (list (cons "format" "JSON")))))

(defun body-string (body)
  (etypecase body
    (string body)
    ((vector (unsigned-byte 8)) (babel:octets-to-string body :encoding :utf-8))))

(defun json-children (value)
  (cond
    ((and (consp value) (eq (car value) :obj)) (mapcar #'cdr (cdr value)))
    ((and (consp value) (eq (car value) :array)) (cdr value))
    (t nil)))

(defun find-json-key (value key)
  (cond
    ((and (consp value) (eq (car value) :obj))
     (or (cdr (assoc key (cdr value) :test #'string-equal))
         (loop for child in (json-children value)
               for found = (find-json-key child key)
               when found return found)))
    ((and (consp value) (eq (car value) :array))
     (loop for child in (cdr value)
           for found = (find-json-key child key)
           when found return found))
    (t nil)))

(defun service-error-code (parsed)
  (let ((results (non-empty-string (find-json-key parsed "TransmissionResults"))))
    (when results
      (find-if (lambda (token)
                 (and (= (length token) 4)
                      (member (subseq token 0 2) '("GE" "SE") :test #'string=)
                      (every #'digit-char-p (subseq token 2))))
               (uiop:split-string (string-upcase results)
                                  :separator '(#\Space #\Comma #\Semicolon #\Colon #\|))))))

(defun perform-melissa-lookup (config entity options)
  (let* ((service (string-downcase (or (option options :service)
                                       "personator-search")))
         (base (endpoint service))
         (input (entity-input entity)))
    (unless base
      (error 'melissa-transport-error
             :message (format nil "Unsupported Melissa service ~S." service)
             :retryable-p nil))
    (unless (non-empty-string (melissa-config-license-key config))
      (error 'melissa-transport-error
             :message "QUASAR_MELISSA_LICENSE_KEY is not configured."
             :retryable-p nil))
    (unless (required-input-present-p service input)
      (error 'melissa-transport-error
             :message (format nil "Melissa ~A could not extract required input from ~A."
                              service
                              (canonical-entity-title entity))
             :retryable-p nil))
    (let* ((query (build-query (service-pairs service config input options)))
           (url (format nil "~A?~A" base query)))
      (handler-case
          (multiple-value-bind (body status headers final-uri)
              (dex:get url
                       :headers '(("Accept" . "application/json"))
                       :connect-timeout (melissa-config-connect-timeout config)
                       :read-timeout (melissa-config-read-timeout config))
            (declare (ignore headers final-uri))
            (let ((parsed
                    (handler-case
                        (jsown:parse (body-string body))
                      (error (condition)
                        (error 'melissa-transport-error
                               :message (format nil "Malformed Melissa JSON response: ~A" condition)
                               :retryable-p nil)))))
              (when-let ((code (service-error-code parsed)))
                (error 'melissa-transport-error
                       :message (format nil "Melissa ~A returned service error ~A." service code)
                       :retryable-p (string= (subseq code 0 2) "SE")))
              (values parsed
                      (json-object
                       (cons "service" service)
                       (cons "http_status" status)
                       (cons "endpoint" base)))))
        (melissa-transport-error (condition)
          (error condition))
        (dex:http-request-failed (condition)
          (let ((status (dex:response-status condition)))
            (error 'melissa-transport-error
                   :message (format nil "Melissa ~A returned HTTP ~D." service status)
                   :retryable-p (or (= status 408)
                                    (= status 429)
                                    (<= 500 status 599)))))
        (error (condition)
          (error 'melissa-transport-error
                 :message (format nil "Melissa ~A network failure: ~A" service condition)
                 :retryable-p t))))))
