(in-package #:quasar.store)

(defparameter *query-max-records* 250)
(defparameter *query-max-bytes* (* 512 1024))
(defparameter *query-max-scanned* 1000)
(defparameter *query-max-milliseconds* 50)
(defparameter *query-max-filter-integer-bits* 4096)
(defparameter *query-max-scope-bytes* 8192)
(defparameter *query-max-cursor-characters* 16000)
(defparameter *query-clock* #'get-internal-real-time)

(dolist (code '("query.invalid" "query.invalid-cursor" "query.stale-cursor"
                "query.record-too-large" "query.deadline" "query.unsupported-store"))
  (pushnew code quasar.protocol::+error-codes+ :test #'string=))

(defgeneric workspace-bootstrap (store workspace-id))
(defgeneric search-documents (store workspace-id request))
(defgeneric fetch-document-batch (store workspace-id request))

(defun %query-error (code message)
  (error 'quasar.protocol:quasar-error :code code :message message))

(defmethod workspace-bootstrap ((store workspace-store) workspace-id)
  (declare (ignore workspace-id))
  (%query-error "query.unsupported-store" "Bounded reads require the Tek9 store."))

(defmethod search-documents ((store workspace-store) workspace-id request)
  (declare (ignore workspace-id request))
  (%query-error "query.unsupported-store" "Bounded reads require the Tek9 store."))

(defmethod fetch-document-batch ((store workspace-store) workspace-id request)
  (declare (ignore workspace-id request))
  (%query-error "query.unsupported-store" "Bounded reads require the Tek9 store."))

(defun %read-meta (database workspace-id)
  (let ((meta (tek9:fetch* database (%workspace-meta-key workspace-id))))
    (when (and meta (not (eql +tek9-schema-version+
                             (quasar.protocol:json-value meta "storageSchemaVersion"))))
      (%query-error "storage.unsupported-schema" "Unsupported workspace storage schema."))
    (or meta (%default-workspace-meta workspace-id 0 0))))

(defmethod workspace-bootstrap ((store tek9-store) workspace-id)
  "Read exactly one durable metadata record; do not restore graphs or documents."
  (let ((database (tek9-store-database store)))
    (tek9:with-read-transaction (database)
      (let ((meta (%read-meta database workspace-id)))
        (quasar.protocol:json-object
         (cons "id" workspace-id)
         (cons "revision" (quasar.protocol:json-value meta "revision" 0))
         (cons "documentCount" (quasar.protocol:json-value meta "documentCount" :null))
         (cons "savedGraphId" (quasar.protocol:json-value meta "activeGraphId" :null))
         (cons "limits" (quasar.protocol:json-object
                         (cons "pageRecords" *query-max-records*)
                         (cons "responseBytes" *query-max-bytes*)
                         (cons "scanRecords" *query-max-scanned*)
                         (cons "scanMilliseconds" *query-max-milliseconds*))))))))

(defun %query-integer (request field default minimum maximum)
  (let ((value (quasar.protocol:json-value request field default)))
    (unless (and (integerp value) (<= minimum value maximum))
      (%query-error "query.invalid" (format nil "~A must be between ~D and ~D." field minimum maximum)))
    value))

(defun %query-string (value field &optional (maximum 512))
  (unless (and (stringp value) (<= (length value) maximum))
    (%query-error "query.invalid" (format nil "~A must be a string of at most ~D characters." field maximum)))
  value)

(defun %query-keys (request allowed)
  (quasar.protocol:ensure-object request "request" "query.invalid")
  (dolist (pair (rest request))
    (unless (member (car pair) allowed :test #'string=)
      (%query-error "query.invalid" (format nil "Unsupported query option ~A." (car pair))))))

(defun %bounded-filter-integer-p (value)
  ;; Bound magnitude before converting arbitrary-precision integers to JSON.
  (and (integerp value) (<= (integer-length value) *query-max-filter-integer-bits*)))

(defun %search-scope (request)
  (let* ((q (%query-string (quasar.protocol:json-value request "q" "") "q" 256))
         (dtype (%query-string (quasar.protocol:json-value request "dtype" "") "dtype" 64))
         (predicate (%query-string (quasar.protocol:json-value request "predicate" "") "predicate" 128))
         (datasets (quasar.protocol:ensure-array
                    (quasar.protocol:json-value request "datasets" (quasar.protocol:json-array))
                    "datasets" "query.invalid"))
         (names (quasar.workspace:array-elements datasets))
         (fields (quasar.protocol:ensure-object
                  (quasar.protocol:json-value request "fields" (quasar.protocol:empty-object))
                  "fields" "query.invalid")))
    (when (> (length names) 16)
      (%query-error "query.invalid" "At most 16 dataset filters are allowed."))
    (dolist (name names) (%query-string name "dataset" 128))
    (when (> (length (rest fields)) 16)
      (%query-error "query.invalid" "At most 16 exact field filters are allowed."))
    (dolist (pair (rest fields))
      (%query-string (car pair) "field" 64)
      (unless (or (and (stringp (cdr pair)) (<= (length (cdr pair)) 256))
                  (%bounded-filter-integer-p (cdr pair)) (member (cdr pair) '(t :true :false :null)))
        (%query-error "query.invalid" "Field filters must be bounded scalar values.")))
    (let ((scope (quasar.protocol:json-object
                  (cons "q" (string-downcase q)) (cons "dtype" dtype)
                  (cons "predicate" predicate)
                  (cons "datasets" (cons :array (sort (remove-duplicates (copy-list names) :test #'string=) #'string<)))
                  (cons "fields" (cons :obj (sort (copy-list (rest fields)) #'string< :key #'car))))))
      (dolist (field '("updatedAfter" "updatedBefore"))
        (let ((value (quasar.protocol:json-value request field :null)))
          (unless (or (eq value :null) (%bounded-filter-integer-p value))
            (%query-error "query.invalid" "Time filters must be bounded integer Unix timestamps."))
          (quasar.protocol:object-set scope field value)))
      (when (> (%utf8-length (quasar.protocol:encode scope)) *query-max-scope-bytes*)
        (%query-error "query.invalid" "Encoded query filters exceed the scope budget."))
      scope)))

(defun %document-matches-scope-p (document scope)
  (let ((datasets (quasar.workspace:array-elements (quasar.protocol:json-value scope "datasets")))
        (dtype (quasar.protocol:json-value scope "dtype"))
        (predicate (quasar.protocol:json-value scope "predicate"))
        (q (quasar.protocol:json-value scope "q"))
        (after (quasar.protocol:json-value scope "updatedAfter"))
        (before (quasar.protocol:json-value scope "updatedBefore"))
        (updated (quasar.protocol:json-value document "updatedAt")))
    (and (or (null datasets) (member (quasar.protocol:json-value document "dataset") datasets :test #'equal))
         (or (zerop (length dtype)) (equal dtype (quasar.protocol:json-value document "dtype")))
         (or (zerop (length predicate)) (equal predicate (quasar.protocol:json-value document "predicate")))
         (or (eq after :null) (and (integerp updated) (>= updated after)))
         (or (eq before :null) (and (integerp updated) (<= updated before)))
         (every (lambda (pair) (equal (cdr pair) (quasar.protocol:json-value document (car pair) :missing)))
                (rest (quasar.protocol:json-value scope "fields")))
         (or (zerop (length q))
             (some (lambda (pair)
                     (and (stringp (cdr pair)) (search q (cdr pair) :test #'char-equal)))
                   (rest document))))))

(defun %search-projection (document)
  "Search rows are projections, never relabeled as complete canonical records."
  (cons :obj
        (loop for field in '("id" "dtype" "dataset" "schemaVersion" "name" "title" "summary"
                            "updatedAt" "predicate" "source" "destination")
              for value = (quasar.protocol:json-value document field :missing)
              unless (eq value :missing)
                collect (cons field (if (and (stringp value) (member field '("name" "title" "summary") :test #'string=))
                                        (subseq value 0 (min 256 (length value)))
                                        (quasar.protocol:clone-json value))))))

(defun %search-cursor (workspace-id revision scope key)
  (let ((cursor (quasar.protocol:encode
                 (quasar.protocol:json-object
                  (cons "v" 1) (cons "workspace" workspace-id)
                  (cons "revision" revision) (cons "scope" scope) (cons "after" key)))))
    (when (> (length cursor) *query-max-cursor-characters*)
      (%query-error "query.invalid" "Query cannot produce a bounded continuation token."))
    cursor))

(defun %cursor-start (request workspace-id revision scope prefix)
  (let ((cursor (quasar.protocol:json-value request "cursor" nil)))
    (when cursor
      (unless (and (stringp cursor) (<= (length cursor) *query-max-cursor-characters*))
        (%query-error "query.invalid-cursor" "Invalid continuation token."))
      (let ((token (handler-case (jsown:with-injective-reader (jsown:parse cursor))
                     (error () (%query-error "query.invalid-cursor" "Malformed continuation token.")))))
        (unless (and (eql 1 (quasar.protocol:json-value token "v"))
                     (equal workspace-id (quasar.protocol:json-value token "workspace"))
                     (string= (quasar.protocol:encode scope)
                              (quasar.protocol:encode (quasar.protocol:json-value token "scope")))
                     (stringp (quasar.protocol:json-value token "after"))
                     (%prefix-p prefix (quasar.protocol:json-value token "after")))
          (%query-error "query.invalid-cursor" "Continuation scope does not match this query."))
        (unless (eql revision (quasar.protocol:json-value token "revision"))
          (%query-error "query.stale-cursor" "Workspace changed; restart the query."))
        (quasar.protocol:json-value token "after")))))

(defmethod search-documents ((store tek9-store) workspace-id request)
  (%query-keys request '("q" "dtype" "predicate" "datasets" "fields" "updatedAfter" "updatedBefore"
                         "limit" "byteLimit" "scanLimit" "deadlineMs" "cursor"))
  (let* ((limit (%query-integer request "limit" 50 1 *query-max-records*))
         (byte-limit (%query-integer request "byteLimit" *query-max-bytes* 32768 *query-max-bytes*))
         (scan-limit (%query-integer request "scanLimit" *query-max-scanned* 1 *query-max-scanned*))
         (milliseconds (%query-integer request "deadlineMs" *query-max-milliseconds* 1 *query-max-milliseconds*))
         (scope (%search-scope request))
         (database (tek9-store-database store))
         (prefix (%document-prefix workspace-id))
         (began (funcall *query-clock*)))
    (tek9:with-read-transaction (database)
      (let* ((revision (quasar.protocol:json-value (%read-meta database workspace-id) "revision" 0))
             (start (or (%cursor-start request workspace-id revision scope prefix) prefix))
             (documents nil) (bytes 0) (scanned 0) (complete nil) (reason "records"))
        (loop
          (when (>= (length documents) limit) (return))
          (when (>= scanned scan-limit) (setf reason "scan-budget") (return))
          (when (>= (* 1000 (- (funcall *query-clock*) began))
                    (* milliseconds internal-time-units-per-second))
            (setf reason "deadline") (return))
          ;; One decoded canonical record at a time, plus Tek9's exclusive-seek
          ;; lookahead. Never retain a batch of large document bodies.
          (let ((row (first (%bounded-range database prefix :start start :limit 1))))
            (unless row (setf complete t reason "complete") (return))
            (incf scanned)
            (when (%document-matches-scope-p (cdr row) scope)
              (let* ((projection (%search-projection (cdr row)))
                     (size (%utf8-length (quasar.protocol:encode projection))))
                (when (> (+ bytes size) (- byte-limit 16384))
                  (unless documents
                    (%query-error "query.record-too-large" "A search row exceeds the response budget."))
                  (setf reason "bytes") (return))
                (push projection documents) (incf bytes size)))
            (setf start (car row))))
        (let ((result (quasar.protocol:json-object
                       (cons "revision" revision) (cons "projection" "search-row.v1")
                       (cons "documents" (cons :array (nreverse documents)))
                       (cons "complete" (if complete t :false))
                       (cons "cursor" (if complete :null (%search-cursor workspace-id revision scope start)))
                       (cons "performance" (quasar.protocol:json-object
                                            (cons "mode" "bounded-primary-scan")
                                            (cons "scanned" scanned) (cons "stopReason" reason)
                                            (cons "documentBytes" bytes)
                                            (cons "elapsedMs" (ceiling (* 1000 (- (funcall *query-clock*) began))
                                                                         internal-time-units-per-second)))))))
          (when (> (%utf8-length (quasar.protocol:encode result)) byte-limit)
            (%query-error "query.record-too-large" "Query continuation exceeds the response budget."))
          result)))))

(defmethod fetch-document-batch ((store tek9-store) workspace-id request)
  (%query-keys request '("ids" "byteLimit" "expectedRevision" "deadlineMs"))
  (let* ((ids (quasar.workspace:array-elements
               (quasar.protocol:ensure-array (quasar.protocol:json-value request "ids" :missing) "ids" "query.invalid")))
         (byte-limit (%query-integer request "byteLimit" *query-max-bytes* 32768 *query-max-bytes*))
         (milliseconds (%query-integer request "deadlineMs" *query-max-milliseconds* 1 *query-max-milliseconds*))
         (began (funcall *query-clock*))
         (database (tek9-store-database store)))
    (when (> (length ids) *query-max-records*)
      (%query-error "query.invalid" "The ID batch exceeds the record limit."))
    (dolist (id ids) (%query-string id "id"))
    (tek9:with-read-transaction (database)
      (let* ((revision (quasar.protocol:json-value (%read-meta database workspace-id) "revision" 0))
             (expected (quasar.protocol:json-value request "expectedRevision" revision))
             (documents nil) (missing nil) (bytes 0))
        (unless (eql expected revision)
          (%query-error "query.stale-cursor" "Workspace changed; restart the batch lookup."))
        (dolist (id (remove-duplicates ids :test #'string=))
          (when (>= (* 1000 (- (funcall *query-clock*) began))
                    (* milliseconds internal-time-units-per-second))
            (%query-error "query.deadline" "ID batch reached its deadline; request fewer IDs."))
          (let ((document (tek9:fetch* database (%document-key workspace-id id))))
            (if document
                (let ((size (%utf8-length (quasar.protocol:encode document))))
                  (incf bytes size)
                  (when (> bytes (- byte-limit 16384))
                    (%query-error "query.record-too-large" "ID batch exceeds the response budget; request fewer IDs."))
                  (push document documents))
                (push id missing))))
        (let ((result (quasar.protocol:json-object
                       (cons "revision" revision) (cons "documents" (cons :array (nreverse documents)))
                       (cons "missingIds" (cons :array (nreverse missing))))))
          (when (> (%utf8-length (quasar.protocol:encode result)) byte-limit)
            (%query-error "query.record-too-large" "ID batch exceeds the response budget."))
          result)))))
